apiVersion: apps/v1
kind: Deployment
metadata:
  name: eltimka-nodeapp-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: eltimka-nodeapp
      tier: client
  template:
    metadata:
      labels:
        app: eltimka-nodeapp
        tier: client
    spec:
      containers:
        - name: eltimka-nodeapp
          image: eltimka/nodeapp:latest
